print("Hello World!")
print(1 + 2)
print(3 * 4)
print()
print("The end")
print("The end", "or is it?", "Keep watching to learn more about python", 3)
print("I am Y and I am making changes for git demo purpose")
print("I hope you understood")
